//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckObservation) DeepCopyInto(out *HealthCheckObservation) {
	*out = *in
	if in.HealthCheckID != nil {
		in, out := &in.HealthCheckID, &out.HealthCheckID
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckState != nil {
		in, out := &in.HealthCheckState, &out.HealthCheckState
		*out = new(string)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(float64)
		**out = **in
	}
	if in.HostName != nil {
		in, out := &in.HostName, &out.HostName
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(float64)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
	if in.URLPath != nil {
		in, out := &in.URLPath, &out.URLPath
		*out = new(string)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckObservation.
func (in *HealthCheckObservation) DeepCopy() *HealthCheckObservation {
	if in == nil {
		return nil
	}
	out := new(HealthCheckObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckParameters) DeepCopyInto(out *HealthCheckParameters) {
	*out = *in
	if in.HealthCheckState != nil {
		in, out := &in.HealthCheckState, &out.HealthCheckState
		*out = new(string)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(float64)
		**out = **in
	}
	if in.HostName != nil {
		in, out := &in.HostName, &out.HostName
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(float64)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
	if in.URLPath != nil {
		in, out := &in.URLPath, &out.URLPath
		*out = new(string)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckParameters.
func (in *HealthCheckParameters) DeepCopy() *HealthCheckParameters {
	if in == nil {
		return nil
	}
	out := new(HealthCheckParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Healthcheck) DeepCopyInto(out *Healthcheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Healthcheck.
func (in *Healthcheck) DeepCopy() *Healthcheck {
	if in == nil {
		return nil
	}
	out := new(Healthcheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Healthcheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthcheckList) DeepCopyInto(out *HealthcheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Healthcheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthcheckList.
func (in *HealthcheckList) DeepCopy() *HealthcheckList {
	if in == nil {
		return nil
	}
	out := new(HealthcheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealthcheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthcheckObservation) DeepCopyInto(out *HealthcheckObservation) {
	*out = *in
	if in.HealthCheckID != nil {
		in, out := &in.HealthCheckID, &out.HealthCheckID
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckState != nil {
		in, out := &in.HealthCheckState, &out.HealthCheckState
		*out = new(string)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(float64)
		**out = **in
	}
	if in.HostName != nil {
		in, out := &in.HostName, &out.HostName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(float64)
		**out = **in
	}
	if in.IsDefaultHostName != nil {
		in, out := &in.IsDefaultHostName, &out.IsDefaultHostName
		*out = new(bool)
		**out = **in
	}
	if in.ListenerID != nil {
		in, out := &in.ListenerID, &out.ListenerID
		*out = new(string)
		**out = **in
	}
	if in.ListenerProtocol != nil {
		in, out := &in.ListenerProtocol, &out.ListenerProtocol
		*out = new(string)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
	if in.URLPath != nil {
		in, out := &in.URLPath, &out.URLPath
		*out = new(string)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthcheckObservation.
func (in *HealthcheckObservation) DeepCopy() *HealthcheckObservation {
	if in == nil {
		return nil
	}
	out := new(HealthcheckObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthcheckParameters) DeepCopyInto(out *HealthcheckParameters) {
	*out = *in
	if in.HealthCheckState != nil {
		in, out := &in.HealthCheckState, &out.HealthCheckState
		*out = new(string)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(float64)
		**out = **in
	}
	if in.HostName != nil {
		in, out := &in.HostName, &out.HostName
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(float64)
		**out = **in
	}
	if in.IsDefaultHostName != nil {
		in, out := &in.IsDefaultHostName, &out.IsDefaultHostName
		*out = new(bool)
		**out = **in
	}
	if in.ListenerID != nil {
		in, out := &in.ListenerID, &out.ListenerID
		*out = new(string)
		**out = **in
	}
	if in.ListenerIDRef != nil {
		in, out := &in.ListenerIDRef, &out.ListenerIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ListenerIDSelector != nil {
		in, out := &in.ListenerIDSelector, &out.ListenerIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
	if in.URLPath != nil {
		in, out := &in.URLPath, &out.URLPath
		*out = new(string)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthcheckParameters.
func (in *HealthcheckParameters) DeepCopy() *HealthcheckParameters {
	if in == nil {
		return nil
	}
	out := new(HealthcheckParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthcheckSpec) DeepCopyInto(out *HealthcheckSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthcheckSpec.
func (in *HealthcheckSpec) DeepCopy() *HealthcheckSpec {
	if in == nil {
		return nil
	}
	out := new(HealthcheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthcheckStatus) DeepCopyInto(out *HealthcheckStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthcheckStatus.
func (in *HealthcheckStatus) DeepCopy() *HealthcheckStatus {
	if in == nil {
		return nil
	}
	out := new(HealthcheckStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LB) DeepCopyInto(out *LB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LB.
func (in *LB) DeepCopy() *LB {
	if in == nil {
		return nil
	}
	out := new(LB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LBList) DeepCopyInto(out *LBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LBList.
func (in *LBList) DeepCopy() *LBList {
	if in == nil {
		return nil
	}
	out := new(LBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LBObservation) DeepCopyInto(out *LBObservation) {
	*out = *in
	if in.AccessLogsEnabled != nil {
		in, out := &in.AccessLogsEnabled, &out.AccessLogsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AccessLogsS3Bucket != nil {
		in, out := &in.AccessLogsS3Bucket, &out.AccessLogsS3Bucket
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IPVersion != nil {
		in, out := &in.IPVersion, &out.IPVersion
		*out = new(string)
		**out = **in
	}
	if in.IsWaf != nil {
		in, out := &in.IsWaf, &out.IsWaf
		*out = new(bool)
		**out = **in
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerState != nil {
		in, out := &in.LoadBalancerState, &out.LoadBalancerState
		*out = new(string)
		**out = **in
	}
	if in.PrivateIPAddress != nil {
		in, out := &in.PrivateIPAddress, &out.PrivateIPAddress
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(float64)
		**out = **in
	}
	if in.PublicIP != nil {
		in, out := &in.PublicIP, &out.PublicIP
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LBObservation.
func (in *LBObservation) DeepCopy() *LBObservation {
	if in == nil {
		return nil
	}
	out := new(LBObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LBParameters) DeepCopyInto(out *LBParameters) {
	*out = *in
	if in.AccessLogsEnabled != nil {
		in, out := &in.AccessLogsEnabled, &out.AccessLogsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AccessLogsS3Bucket != nil {
		in, out := &in.AccessLogsS3Bucket, &out.AccessLogsS3Bucket
		*out = new(string)
		**out = **in
	}
	if in.IPVersion != nil {
		in, out := &in.IPVersion, &out.IPVersion
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerState != nil {
		in, out := &in.LoadBalancerState, &out.LoadBalancerState
		*out = new(string)
		**out = **in
	}
	if in.PrivateIPAddress != nil {
		in, out := &in.PrivateIPAddress, &out.PrivateIPAddress
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(float64)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.VPCIDRef != nil {
		in, out := &in.VPCIDRef, &out.VPCIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCIDSelector != nil {
		in, out := &in.VPCIDSelector, &out.VPCIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LBParameters.
func (in *LBParameters) DeepCopy() *LBParameters {
	if in == nil {
		return nil
	}
	out := new(LBParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LBSpec) DeepCopyInto(out *LBSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LBSpec.
func (in *LBSpec) DeepCopy() *LBSpec {
	if in == nil {
		return nil
	}
	out := new(LBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LBStatus) DeepCopyInto(out *LBStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LBStatus.
func (in *LBStatus) DeepCopy() *LBStatus {
	if in == nil {
		return nil
	}
	out := new(LBStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbAcl) DeepCopyInto(out *LbAcl) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbAcl.
func (in *LbAcl) DeepCopy() *LbAcl {
	if in == nil {
		return nil
	}
	out := new(LbAcl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbAcl) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbAclEntry) DeepCopyInto(out *LbAclEntry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbAclEntry.
func (in *LbAclEntry) DeepCopy() *LbAclEntry {
	if in == nil {
		return nil
	}
	out := new(LbAclEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbAclEntry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbAclEntryList) DeepCopyInto(out *LbAclEntryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LbAclEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbAclEntryList.
func (in *LbAclEntryList) DeepCopy() *LbAclEntryList {
	if in == nil {
		return nil
	}
	out := new(LbAclEntryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbAclEntryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbAclEntryObservation) DeepCopyInto(out *LbAclEntryObservation) {
	*out = *in
	if in.CidrBlock != nil {
		in, out := &in.CidrBlock, &out.CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerACLEntryID != nil {
		in, out := &in.LoadBalancerACLEntryID, &out.LoadBalancerACLEntryID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerACLID != nil {
		in, out := &in.LoadBalancerACLID, &out.LoadBalancerACLID
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.RuleAction != nil {
		in, out := &in.RuleAction, &out.RuleAction
		*out = new(string)
		**out = **in
	}
	if in.RuleNumber != nil {
		in, out := &in.RuleNumber, &out.RuleNumber
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbAclEntryObservation.
func (in *LbAclEntryObservation) DeepCopy() *LbAclEntryObservation {
	if in == nil {
		return nil
	}
	out := new(LbAclEntryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbAclEntryParameters) DeepCopyInto(out *LbAclEntryParameters) {
	*out = *in
	if in.CidrBlock != nil {
		in, out := &in.CidrBlock, &out.CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerACLID != nil {
		in, out := &in.LoadBalancerACLID, &out.LoadBalancerACLID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerACLIDRef != nil {
		in, out := &in.LoadBalancerACLIDRef, &out.LoadBalancerACLIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerACLIDSelector != nil {
		in, out := &in.LoadBalancerACLIDSelector, &out.LoadBalancerACLIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.RuleAction != nil {
		in, out := &in.RuleAction, &out.RuleAction
		*out = new(string)
		**out = **in
	}
	if in.RuleNumber != nil {
		in, out := &in.RuleNumber, &out.RuleNumber
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbAclEntryParameters.
func (in *LbAclEntryParameters) DeepCopy() *LbAclEntryParameters {
	if in == nil {
		return nil
	}
	out := new(LbAclEntryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbAclEntrySpec) DeepCopyInto(out *LbAclEntrySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbAclEntrySpec.
func (in *LbAclEntrySpec) DeepCopy() *LbAclEntrySpec {
	if in == nil {
		return nil
	}
	out := new(LbAclEntrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbAclEntryStatus) DeepCopyInto(out *LbAclEntryStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbAclEntryStatus.
func (in *LbAclEntryStatus) DeepCopy() *LbAclEntryStatus {
	if in == nil {
		return nil
	}
	out := new(LbAclEntryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbAclList) DeepCopyInto(out *LbAclList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LbAcl, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbAclList.
func (in *LbAclList) DeepCopy() *LbAclList {
	if in == nil {
		return nil
	}
	out := new(LbAclList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbAclList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbAclObservation) DeepCopyInto(out *LbAclObservation) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IPVersion != nil {
		in, out := &in.IPVersion, &out.IPVersion
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerACLEntrySet != nil {
		in, out := &in.LoadBalancerACLEntrySet, &out.LoadBalancerACLEntrySet
		*out = make([]LoadBalancerACLEntrySetObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoadBalancerACLID != nil {
		in, out := &in.LoadBalancerACLID, &out.LoadBalancerACLID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerACLName != nil {
		in, out := &in.LoadBalancerACLName, &out.LoadBalancerACLName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbAclObservation.
func (in *LbAclObservation) DeepCopy() *LbAclObservation {
	if in == nil {
		return nil
	}
	out := new(LbAclObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbAclParameters) DeepCopyInto(out *LbAclParameters) {
	*out = *in
	if in.IPVersion != nil {
		in, out := &in.IPVersion, &out.IPVersion
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerACLEntrySet != nil {
		in, out := &in.LoadBalancerACLEntrySet, &out.LoadBalancerACLEntrySet
		*out = make([]LoadBalancerACLEntrySetParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoadBalancerACLName != nil {
		in, out := &in.LoadBalancerACLName, &out.LoadBalancerACLName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbAclParameters.
func (in *LbAclParameters) DeepCopy() *LbAclParameters {
	if in == nil {
		return nil
	}
	out := new(LbAclParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbAclSpec) DeepCopyInto(out *LbAclSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbAclSpec.
func (in *LbAclSpec) DeepCopy() *LbAclSpec {
	if in == nil {
		return nil
	}
	out := new(LbAclSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbAclStatus) DeepCopyInto(out *LbAclStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbAclStatus.
func (in *LbAclStatus) DeepCopy() *LbAclStatus {
	if in == nil {
		return nil
	}
	out := new(LbAclStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbBackendServerGroup) DeepCopyInto(out *LbBackendServerGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbBackendServerGroup.
func (in *LbBackendServerGroup) DeepCopy() *LbBackendServerGroup {
	if in == nil {
		return nil
	}
	out := new(LbBackendServerGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbBackendServerGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbBackendServerGroupList) DeepCopyInto(out *LbBackendServerGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LbBackendServerGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbBackendServerGroupList.
func (in *LbBackendServerGroupList) DeepCopy() *LbBackendServerGroupList {
	if in == nil {
		return nil
	}
	out := new(LbBackendServerGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbBackendServerGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbBackendServerGroupObservation) DeepCopyInto(out *LbBackendServerGroupObservation) {
	*out = *in
	if in.BackendServerGroupID != nil {
		in, out := &in.BackendServerGroupID, &out.BackendServerGroupID
		*out = new(string)
		**out = **in
	}
	if in.BackendServerGroupName != nil {
		in, out := &in.BackendServerGroupName, &out.BackendServerGroupName
		*out = new(string)
		**out = **in
	}
	if in.BackendServerGroupType != nil {
		in, out := &in.BackendServerGroupType, &out.BackendServerGroupType
		*out = new(string)
		**out = **in
	}
	if in.BackendServerNumber != nil {
		in, out := &in.BackendServerNumber, &out.BackendServerNumber
		*out = new(float64)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]HealthCheckObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbBackendServerGroupObservation.
func (in *LbBackendServerGroupObservation) DeepCopy() *LbBackendServerGroupObservation {
	if in == nil {
		return nil
	}
	out := new(LbBackendServerGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbBackendServerGroupParameters) DeepCopyInto(out *LbBackendServerGroupParameters) {
	*out = *in
	if in.BackendServerGroupName != nil {
		in, out := &in.BackendServerGroupName, &out.BackendServerGroupName
		*out = new(string)
		**out = **in
	}
	if in.BackendServerGroupType != nil {
		in, out := &in.BackendServerGroupType, &out.BackendServerGroupType
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]HealthCheckParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.VPCIDRef != nil {
		in, out := &in.VPCIDRef, &out.VPCIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCIDSelector != nil {
		in, out := &in.VPCIDSelector, &out.VPCIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbBackendServerGroupParameters.
func (in *LbBackendServerGroupParameters) DeepCopy() *LbBackendServerGroupParameters {
	if in == nil {
		return nil
	}
	out := new(LbBackendServerGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbBackendServerGroupSpec) DeepCopyInto(out *LbBackendServerGroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbBackendServerGroupSpec.
func (in *LbBackendServerGroupSpec) DeepCopy() *LbBackendServerGroupSpec {
	if in == nil {
		return nil
	}
	out := new(LbBackendServerGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbBackendServerGroupStatus) DeepCopyInto(out *LbBackendServerGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbBackendServerGroupStatus.
func (in *LbBackendServerGroupStatus) DeepCopy() *LbBackendServerGroupStatus {
	if in == nil {
		return nil
	}
	out := new(LbBackendServerGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbHostHeader) DeepCopyInto(out *LbHostHeader) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbHostHeader.
func (in *LbHostHeader) DeepCopy() *LbHostHeader {
	if in == nil {
		return nil
	}
	out := new(LbHostHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbHostHeader) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbHostHeaderList) DeepCopyInto(out *LbHostHeaderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LbHostHeader, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbHostHeaderList.
func (in *LbHostHeaderList) DeepCopy() *LbHostHeaderList {
	if in == nil {
		return nil
	}
	out := new(LbHostHeaderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbHostHeaderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbHostHeaderObservation) DeepCopyInto(out *LbHostHeaderObservation) {
	*out = *in
	if in.CertificateID != nil {
		in, out := &in.CertificateID, &out.CertificateID
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.HostHeader != nil {
		in, out := &in.HostHeader, &out.HostHeader
		*out = new(string)
		**out = **in
	}
	if in.HostHeaderID != nil {
		in, out := &in.HostHeaderID, &out.HostHeaderID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ListenerID != nil {
		in, out := &in.ListenerID, &out.ListenerID
		*out = new(string)
		**out = **in
	}
	if in.ListenerProtocol != nil {
		in, out := &in.ListenerProtocol, &out.ListenerProtocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbHostHeaderObservation.
func (in *LbHostHeaderObservation) DeepCopy() *LbHostHeaderObservation {
	if in == nil {
		return nil
	}
	out := new(LbHostHeaderObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbHostHeaderParameters) DeepCopyInto(out *LbHostHeaderParameters) {
	*out = *in
	if in.CertificateID != nil {
		in, out := &in.CertificateID, &out.CertificateID
		*out = new(string)
		**out = **in
	}
	if in.HostHeader != nil {
		in, out := &in.HostHeader, &out.HostHeader
		*out = new(string)
		**out = **in
	}
	if in.ListenerID != nil {
		in, out := &in.ListenerID, &out.ListenerID
		*out = new(string)
		**out = **in
	}
	if in.ListenerIDRef != nil {
		in, out := &in.ListenerIDRef, &out.ListenerIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ListenerIDSelector != nil {
		in, out := &in.ListenerIDSelector, &out.ListenerIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbHostHeaderParameters.
func (in *LbHostHeaderParameters) DeepCopy() *LbHostHeaderParameters {
	if in == nil {
		return nil
	}
	out := new(LbHostHeaderParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbHostHeaderSpec) DeepCopyInto(out *LbHostHeaderSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbHostHeaderSpec.
func (in *LbHostHeaderSpec) DeepCopy() *LbHostHeaderSpec {
	if in == nil {
		return nil
	}
	out := new(LbHostHeaderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbHostHeaderStatus) DeepCopyInto(out *LbHostHeaderStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbHostHeaderStatus.
func (in *LbHostHeaderStatus) DeepCopy() *LbHostHeaderStatus {
	if in == nil {
		return nil
	}
	out := new(LbHostHeaderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListener) DeepCopyInto(out *LbListener) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListener.
func (in *LbListener) DeepCopy() *LbListener {
	if in == nil {
		return nil
	}
	out := new(LbListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbListener) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerAssociateAcl) DeepCopyInto(out *LbListenerAssociateAcl) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerAssociateAcl.
func (in *LbListenerAssociateAcl) DeepCopy() *LbListenerAssociateAcl {
	if in == nil {
		return nil
	}
	out := new(LbListenerAssociateAcl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbListenerAssociateAcl) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerAssociateAclList) DeepCopyInto(out *LbListenerAssociateAclList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LbListenerAssociateAcl, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerAssociateAclList.
func (in *LbListenerAssociateAclList) DeepCopy() *LbListenerAssociateAclList {
	if in == nil {
		return nil
	}
	out := new(LbListenerAssociateAclList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbListenerAssociateAclList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerAssociateAclObservation) DeepCopyInto(out *LbListenerAssociateAclObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ListenerID != nil {
		in, out := &in.ListenerID, &out.ListenerID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerACLID != nil {
		in, out := &in.LoadBalancerACLID, &out.LoadBalancerACLID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerAssociateAclObservation.
func (in *LbListenerAssociateAclObservation) DeepCopy() *LbListenerAssociateAclObservation {
	if in == nil {
		return nil
	}
	out := new(LbListenerAssociateAclObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerAssociateAclParameters) DeepCopyInto(out *LbListenerAssociateAclParameters) {
	*out = *in
	if in.ListenerID != nil {
		in, out := &in.ListenerID, &out.ListenerID
		*out = new(string)
		**out = **in
	}
	if in.ListenerIDRef != nil {
		in, out := &in.ListenerIDRef, &out.ListenerIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ListenerIDSelector != nil {
		in, out := &in.ListenerIDSelector, &out.ListenerIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerACLID != nil {
		in, out := &in.LoadBalancerACLID, &out.LoadBalancerACLID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerACLIDRef != nil {
		in, out := &in.LoadBalancerACLIDRef, &out.LoadBalancerACLIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerACLIDSelector != nil {
		in, out := &in.LoadBalancerACLIDSelector, &out.LoadBalancerACLIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerAssociateAclParameters.
func (in *LbListenerAssociateAclParameters) DeepCopy() *LbListenerAssociateAclParameters {
	if in == nil {
		return nil
	}
	out := new(LbListenerAssociateAclParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerAssociateAclSpec) DeepCopyInto(out *LbListenerAssociateAclSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerAssociateAclSpec.
func (in *LbListenerAssociateAclSpec) DeepCopy() *LbListenerAssociateAclSpec {
	if in == nil {
		return nil
	}
	out := new(LbListenerAssociateAclSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerAssociateAclStatus) DeepCopyInto(out *LbListenerAssociateAclStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerAssociateAclStatus.
func (in *LbListenerAssociateAclStatus) DeepCopy() *LbListenerAssociateAclStatus {
	if in == nil {
		return nil
	}
	out := new(LbListenerAssociateAclStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerHealthCheckObservation) DeepCopyInto(out *LbListenerHealthCheckObservation) {
	*out = *in
	if in.HealthCheckID != nil {
		in, out := &in.HealthCheckID, &out.HealthCheckID
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckState != nil {
		in, out := &in.HealthCheckState, &out.HealthCheckState
		*out = new(string)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(float64)
		**out = **in
	}
	if in.HostName != nil {
		in, out := &in.HostName, &out.HostName
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(float64)
		**out = **in
	}
	if in.IsDefaultHostName != nil {
		in, out := &in.IsDefaultHostName, &out.IsDefaultHostName
		*out = new(bool)
		**out = **in
	}
	if in.ListenerID != nil {
		in, out := &in.ListenerID, &out.ListenerID
		*out = new(string)
		**out = **in
	}
	if in.ListenerProtocol != nil {
		in, out := &in.ListenerProtocol, &out.ListenerProtocol
		*out = new(string)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
	if in.URLPath != nil {
		in, out := &in.URLPath, &out.URLPath
		*out = new(string)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerHealthCheckObservation.
func (in *LbListenerHealthCheckObservation) DeepCopy() *LbListenerHealthCheckObservation {
	if in == nil {
		return nil
	}
	out := new(LbListenerHealthCheckObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerHealthCheckParameters) DeepCopyInto(out *LbListenerHealthCheckParameters) {
	*out = *in
	if in.HealthCheckState != nil {
		in, out := &in.HealthCheckState, &out.HealthCheckState
		*out = new(string)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(float64)
		**out = **in
	}
	if in.HostName != nil {
		in, out := &in.HostName, &out.HostName
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(float64)
		**out = **in
	}
	if in.IsDefaultHostName != nil {
		in, out := &in.IsDefaultHostName, &out.IsDefaultHostName
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
	if in.URLPath != nil {
		in, out := &in.URLPath, &out.URLPath
		*out = new(string)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerHealthCheckParameters.
func (in *LbListenerHealthCheckParameters) DeepCopy() *LbListenerHealthCheckParameters {
	if in == nil {
		return nil
	}
	out := new(LbListenerHealthCheckParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerList) DeepCopyInto(out *LbListenerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LbListener, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerList.
func (in *LbListenerList) DeepCopy() *LbListenerList {
	if in == nil {
		return nil
	}
	out := new(LbListenerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbListenerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerObservation) DeepCopyInto(out *LbListenerObservation) {
	*out = *in
	if in.CertificateID != nil {
		in, out := &in.CertificateID, &out.CertificateID
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.EnableHttp2 != nil {
		in, out := &in.EnableHttp2, &out.EnableHttp2
		*out = new(bool)
		**out = **in
	}
	if in.HTTPProtocol != nil {
		in, out := &in.HTTPProtocol, &out.HTTPProtocol
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]LbListenerHealthCheckObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ListenerID != nil {
		in, out := &in.ListenerID, &out.ListenerID
		*out = new(string)
		**out = **in
	}
	if in.ListenerName != nil {
		in, out := &in.ListenerName, &out.ListenerName
		*out = new(string)
		**out = **in
	}
	if in.ListenerPort != nil {
		in, out := &in.ListenerPort, &out.ListenerPort
		*out = new(float64)
		**out = **in
	}
	if in.ListenerProtocol != nil {
		in, out := &in.ListenerProtocol, &out.ListenerProtocol
		*out = new(string)
		**out = **in
	}
	if in.ListenerState != nil {
		in, out := &in.ListenerState, &out.ListenerState
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerACLID != nil {
		in, out := &in.LoadBalancerACLID, &out.LoadBalancerACLID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.RedirectListenerID != nil {
		in, out := &in.RedirectListenerID, &out.RedirectListenerID
		*out = new(string)
		**out = **in
	}
	if in.Session != nil {
		in, out := &in.Session, &out.Session
		*out = make([]SessionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TLSCipherPolicy != nil {
		in, out := &in.TLSCipherPolicy, &out.TLSCipherPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerObservation.
func (in *LbListenerObservation) DeepCopy() *LbListenerObservation {
	if in == nil {
		return nil
	}
	out := new(LbListenerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerParameters) DeepCopyInto(out *LbListenerParameters) {
	*out = *in
	if in.CertificateID != nil {
		in, out := &in.CertificateID, &out.CertificateID
		*out = new(string)
		**out = **in
	}
	if in.EnableHttp2 != nil {
		in, out := &in.EnableHttp2, &out.EnableHttp2
		*out = new(bool)
		**out = **in
	}
	if in.HTTPProtocol != nil {
		in, out := &in.HTTPProtocol, &out.HTTPProtocol
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]LbListenerHealthCheckParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ListenerName != nil {
		in, out := &in.ListenerName, &out.ListenerName
		*out = new(string)
		**out = **in
	}
	if in.ListenerPort != nil {
		in, out := &in.ListenerPort, &out.ListenerPort
		*out = new(float64)
		**out = **in
	}
	if in.ListenerProtocol != nil {
		in, out := &in.ListenerProtocol, &out.ListenerProtocol
		*out = new(string)
		**out = **in
	}
	if in.ListenerState != nil {
		in, out := &in.ListenerState, &out.ListenerState
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerACLID != nil {
		in, out := &in.LoadBalancerACLID, &out.LoadBalancerACLID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerACLIDRef != nil {
		in, out := &in.LoadBalancerACLIDRef, &out.LoadBalancerACLIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerACLIDSelector != nil {
		in, out := &in.LoadBalancerACLIDSelector, &out.LoadBalancerACLIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerIDRef != nil {
		in, out := &in.LoadBalancerIDRef, &out.LoadBalancerIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerIDSelector != nil {
		in, out := &in.LoadBalancerIDSelector, &out.LoadBalancerIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.RedirectListenerID != nil {
		in, out := &in.RedirectListenerID, &out.RedirectListenerID
		*out = new(string)
		**out = **in
	}
	if in.Session != nil {
		in, out := &in.Session, &out.Session
		*out = make([]SessionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TLSCipherPolicy != nil {
		in, out := &in.TLSCipherPolicy, &out.TLSCipherPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerParameters.
func (in *LbListenerParameters) DeepCopy() *LbListenerParameters {
	if in == nil {
		return nil
	}
	out := new(LbListenerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerServer) DeepCopyInto(out *LbListenerServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerServer.
func (in *LbListenerServer) DeepCopy() *LbListenerServer {
	if in == nil {
		return nil
	}
	out := new(LbListenerServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbListenerServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerServerList) DeepCopyInto(out *LbListenerServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LbListenerServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerServerList.
func (in *LbListenerServerList) DeepCopy() *LbListenerServerList {
	if in == nil {
		return nil
	}
	out := new(LbListenerServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbListenerServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerServerObservation) DeepCopyInto(out *LbListenerServerObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.ListenerID != nil {
		in, out := &in.ListenerID, &out.ListenerID
		*out = new(string)
		**out = **in
	}
	if in.ListenerMethod != nil {
		in, out := &in.ListenerMethod, &out.ListenerMethod
		*out = new(string)
		**out = **in
	}
	if in.MasterSlaveType != nil {
		in, out := &in.MasterSlaveType, &out.MasterSlaveType
		*out = new(string)
		**out = **in
	}
	if in.RealServerIP != nil {
		in, out := &in.RealServerIP, &out.RealServerIP
		*out = new(string)
		**out = **in
	}
	if in.RealServerPort != nil {
		in, out := &in.RealServerPort, &out.RealServerPort
		*out = new(float64)
		**out = **in
	}
	if in.RealServerState != nil {
		in, out := &in.RealServerState, &out.RealServerState
		*out = new(string)
		**out = **in
	}
	if in.RealServerType != nil {
		in, out := &in.RealServerType, &out.RealServerType
		*out = new(string)
		**out = **in
	}
	if in.RegisterID != nil {
		in, out := &in.RegisterID, &out.RegisterID
		*out = new(string)
		**out = **in
	}
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerServerObservation.
func (in *LbListenerServerObservation) DeepCopy() *LbListenerServerObservation {
	if in == nil {
		return nil
	}
	out := new(LbListenerServerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerServerParameters) DeepCopyInto(out *LbListenerServerParameters) {
	*out = *in
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.ListenerID != nil {
		in, out := &in.ListenerID, &out.ListenerID
		*out = new(string)
		**out = **in
	}
	if in.ListenerIDRef != nil {
		in, out := &in.ListenerIDRef, &out.ListenerIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ListenerIDSelector != nil {
		in, out := &in.ListenerIDSelector, &out.ListenerIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MasterSlaveType != nil {
		in, out := &in.MasterSlaveType, &out.MasterSlaveType
		*out = new(string)
		**out = **in
	}
	if in.RealServerIP != nil {
		in, out := &in.RealServerIP, &out.RealServerIP
		*out = new(string)
		**out = **in
	}
	if in.RealServerPort != nil {
		in, out := &in.RealServerPort, &out.RealServerPort
		*out = new(float64)
		**out = **in
	}
	if in.RealServerType != nil {
		in, out := &in.RealServerType, &out.RealServerType
		*out = new(string)
		**out = **in
	}
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerServerParameters.
func (in *LbListenerServerParameters) DeepCopy() *LbListenerServerParameters {
	if in == nil {
		return nil
	}
	out := new(LbListenerServerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerServerSpec) DeepCopyInto(out *LbListenerServerSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerServerSpec.
func (in *LbListenerServerSpec) DeepCopy() *LbListenerServerSpec {
	if in == nil {
		return nil
	}
	out := new(LbListenerServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerServerStatus) DeepCopyInto(out *LbListenerServerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerServerStatus.
func (in *LbListenerServerStatus) DeepCopy() *LbListenerServerStatus {
	if in == nil {
		return nil
	}
	out := new(LbListenerServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerSpec) DeepCopyInto(out *LbListenerSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerSpec.
func (in *LbListenerSpec) DeepCopy() *LbListenerSpec {
	if in == nil {
		return nil
	}
	out := new(LbListenerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbListenerStatus) DeepCopyInto(out *LbListenerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbListenerStatus.
func (in *LbListenerStatus) DeepCopy() *LbListenerStatus {
	if in == nil {
		return nil
	}
	out := new(LbListenerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRegisterBackendServer) DeepCopyInto(out *LbRegisterBackendServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRegisterBackendServer.
func (in *LbRegisterBackendServer) DeepCopy() *LbRegisterBackendServer {
	if in == nil {
		return nil
	}
	out := new(LbRegisterBackendServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbRegisterBackendServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRegisterBackendServerList) DeepCopyInto(out *LbRegisterBackendServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LbRegisterBackendServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRegisterBackendServerList.
func (in *LbRegisterBackendServerList) DeepCopy() *LbRegisterBackendServerList {
	if in == nil {
		return nil
	}
	out := new(LbRegisterBackendServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbRegisterBackendServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRegisterBackendServerObservation) DeepCopyInto(out *LbRegisterBackendServerObservation) {
	*out = *in
	if in.BackendServerGroupID != nil {
		in, out := &in.BackendServerGroupID, &out.BackendServerGroupID
		*out = new(string)
		**out = **in
	}
	if in.BackendServerIP != nil {
		in, out := &in.BackendServerIP, &out.BackendServerIP
		*out = new(string)
		**out = **in
	}
	if in.BackendServerPort != nil {
		in, out := &in.BackendServerPort, &out.BackendServerPort
		*out = new(float64)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.NetworkInterfaceID != nil {
		in, out := &in.NetworkInterfaceID, &out.NetworkInterfaceID
		*out = new(string)
		**out = **in
	}
	if in.RealServerIP != nil {
		in, out := &in.RealServerIP, &out.RealServerIP
		*out = new(float64)
		**out = **in
	}
	if in.RealServerPort != nil {
		in, out := &in.RealServerPort, &out.RealServerPort
		*out = new(string)
		**out = **in
	}
	if in.RealServerState != nil {
		in, out := &in.RealServerState, &out.RealServerState
		*out = new(string)
		**out = **in
	}
	if in.RealServerType != nil {
		in, out := &in.RealServerType, &out.RealServerType
		*out = new(string)
		**out = **in
	}
	if in.RegisterID != nil {
		in, out := &in.RegisterID, &out.RegisterID
		*out = new(string)
		**out = **in
	}
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRegisterBackendServerObservation.
func (in *LbRegisterBackendServerObservation) DeepCopy() *LbRegisterBackendServerObservation {
	if in == nil {
		return nil
	}
	out := new(LbRegisterBackendServerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRegisterBackendServerParameters) DeepCopyInto(out *LbRegisterBackendServerParameters) {
	*out = *in
	if in.BackendServerGroupID != nil {
		in, out := &in.BackendServerGroupID, &out.BackendServerGroupID
		*out = new(string)
		**out = **in
	}
	if in.BackendServerGroupIDRef != nil {
		in, out := &in.BackendServerGroupIDRef, &out.BackendServerGroupIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.BackendServerGroupIDSelector != nil {
		in, out := &in.BackendServerGroupIDSelector, &out.BackendServerGroupIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.BackendServerIP != nil {
		in, out := &in.BackendServerIP, &out.BackendServerIP
		*out = new(string)
		**out = **in
	}
	if in.BackendServerPort != nil {
		in, out := &in.BackendServerPort, &out.BackendServerPort
		*out = new(float64)
		**out = **in
	}
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRegisterBackendServerParameters.
func (in *LbRegisterBackendServerParameters) DeepCopy() *LbRegisterBackendServerParameters {
	if in == nil {
		return nil
	}
	out := new(LbRegisterBackendServerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRegisterBackendServerSpec) DeepCopyInto(out *LbRegisterBackendServerSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRegisterBackendServerSpec.
func (in *LbRegisterBackendServerSpec) DeepCopy() *LbRegisterBackendServerSpec {
	if in == nil {
		return nil
	}
	out := new(LbRegisterBackendServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRegisterBackendServerStatus) DeepCopyInto(out *LbRegisterBackendServerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRegisterBackendServerStatus.
func (in *LbRegisterBackendServerStatus) DeepCopy() *LbRegisterBackendServerStatus {
	if in == nil {
		return nil
	}
	out := new(LbRegisterBackendServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRule) DeepCopyInto(out *LbRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRule.
func (in *LbRule) DeepCopy() *LbRule {
	if in == nil {
		return nil
	}
	out := new(LbRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRuleHealthCheckObservation) DeepCopyInto(out *LbRuleHealthCheckObservation) {
	*out = *in
	if in.HealthCheckID != nil {
		in, out := &in.HealthCheckID, &out.HealthCheckID
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckState != nil {
		in, out := &in.HealthCheckState, &out.HealthCheckState
		*out = new(string)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(float64)
		**out = **in
	}
	if in.HostName != nil {
		in, out := &in.HostName, &out.HostName
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(float64)
		**out = **in
	}
	if in.IsDefaultHostName != nil {
		in, out := &in.IsDefaultHostName, &out.IsDefaultHostName
		*out = new(bool)
		**out = **in
	}
	if in.ListenerProtocol != nil {
		in, out := &in.ListenerProtocol, &out.ListenerProtocol
		*out = new(string)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
	if in.URLPath != nil {
		in, out := &in.URLPath, &out.URLPath
		*out = new(string)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRuleHealthCheckObservation.
func (in *LbRuleHealthCheckObservation) DeepCopy() *LbRuleHealthCheckObservation {
	if in == nil {
		return nil
	}
	out := new(LbRuleHealthCheckObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRuleHealthCheckParameters) DeepCopyInto(out *LbRuleHealthCheckParameters) {
	*out = *in
	if in.HealthCheckState != nil {
		in, out := &in.HealthCheckState, &out.HealthCheckState
		*out = new(string)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(float64)
		**out = **in
	}
	if in.HostName != nil {
		in, out := &in.HostName, &out.HostName
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(float64)
		**out = **in
	}
	if in.IsDefaultHostName != nil {
		in, out := &in.IsDefaultHostName, &out.IsDefaultHostName
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
	if in.URLPath != nil {
		in, out := &in.URLPath, &out.URLPath
		*out = new(string)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRuleHealthCheckParameters.
func (in *LbRuleHealthCheckParameters) DeepCopy() *LbRuleHealthCheckParameters {
	if in == nil {
		return nil
	}
	out := new(LbRuleHealthCheckParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRuleList) DeepCopyInto(out *LbRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LbRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRuleList.
func (in *LbRuleList) DeepCopy() *LbRuleList {
	if in == nil {
		return nil
	}
	out := new(LbRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LbRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRuleObservation) DeepCopyInto(out *LbRuleObservation) {
	*out = *in
	if in.BackendServerGroupID != nil {
		in, out := &in.BackendServerGroupID, &out.BackendServerGroupID
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]LbRuleHealthCheckObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HostHeaderID != nil {
		in, out := &in.HostHeaderID, &out.HostHeaderID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ListenerSync != nil {
		in, out := &in.ListenerSync, &out.ListenerSync
		*out = new(string)
		**out = **in
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.RuleID != nil {
		in, out := &in.RuleID, &out.RuleID
		*out = new(string)
		**out = **in
	}
	if in.Session != nil {
		in, out := &in.Session, &out.Session
		*out = make([]LbRuleSessionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRuleObservation.
func (in *LbRuleObservation) DeepCopy() *LbRuleObservation {
	if in == nil {
		return nil
	}
	out := new(LbRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRuleParameters) DeepCopyInto(out *LbRuleParameters) {
	*out = *in
	if in.BackendServerGroupID != nil {
		in, out := &in.BackendServerGroupID, &out.BackendServerGroupID
		*out = new(string)
		**out = **in
	}
	if in.BackendServerGroupIDRef != nil {
		in, out := &in.BackendServerGroupIDRef, &out.BackendServerGroupIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.BackendServerGroupIDSelector != nil {
		in, out := &in.BackendServerGroupIDSelector, &out.BackendServerGroupIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]LbRuleHealthCheckParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HostHeaderID != nil {
		in, out := &in.HostHeaderID, &out.HostHeaderID
		*out = new(string)
		**out = **in
	}
	if in.HostHeaderIDRef != nil {
		in, out := &in.HostHeaderIDRef, &out.HostHeaderIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.HostHeaderIDSelector != nil {
		in, out := &in.HostHeaderIDSelector, &out.HostHeaderIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ListenerSync != nil {
		in, out := &in.ListenerSync, &out.ListenerSync
		*out = new(string)
		**out = **in
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Session != nil {
		in, out := &in.Session, &out.Session
		*out = make([]LbRuleSessionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRuleParameters.
func (in *LbRuleParameters) DeepCopy() *LbRuleParameters {
	if in == nil {
		return nil
	}
	out := new(LbRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRuleSessionObservation) DeepCopyInto(out *LbRuleSessionObservation) {
	*out = *in
	if in.CookieName != nil {
		in, out := &in.CookieName, &out.CookieName
		*out = new(string)
		**out = **in
	}
	if in.CookieType != nil {
		in, out := &in.CookieType, &out.CookieType
		*out = new(string)
		**out = **in
	}
	if in.SessionPersistencePeriod != nil {
		in, out := &in.SessionPersistencePeriod, &out.SessionPersistencePeriod
		*out = new(float64)
		**out = **in
	}
	if in.SessionState != nil {
		in, out := &in.SessionState, &out.SessionState
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRuleSessionObservation.
func (in *LbRuleSessionObservation) DeepCopy() *LbRuleSessionObservation {
	if in == nil {
		return nil
	}
	out := new(LbRuleSessionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRuleSessionParameters) DeepCopyInto(out *LbRuleSessionParameters) {
	*out = *in
	if in.CookieName != nil {
		in, out := &in.CookieName, &out.CookieName
		*out = new(string)
		**out = **in
	}
	if in.CookieType != nil {
		in, out := &in.CookieType, &out.CookieType
		*out = new(string)
		**out = **in
	}
	if in.SessionPersistencePeriod != nil {
		in, out := &in.SessionPersistencePeriod, &out.SessionPersistencePeriod
		*out = new(float64)
		**out = **in
	}
	if in.SessionState != nil {
		in, out := &in.SessionState, &out.SessionState
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRuleSessionParameters.
func (in *LbRuleSessionParameters) DeepCopy() *LbRuleSessionParameters {
	if in == nil {
		return nil
	}
	out := new(LbRuleSessionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRuleSpec) DeepCopyInto(out *LbRuleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRuleSpec.
func (in *LbRuleSpec) DeepCopy() *LbRuleSpec {
	if in == nil {
		return nil
	}
	out := new(LbRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbRuleStatus) DeepCopyInto(out *LbRuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbRuleStatus.
func (in *LbRuleStatus) DeepCopy() *LbRuleStatus {
	if in == nil {
		return nil
	}
	out := new(LbRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerACLEntrySetObservation) DeepCopyInto(out *LoadBalancerACLEntrySetObservation) {
	*out = *in
	if in.CidrBlock != nil {
		in, out := &in.CidrBlock, &out.CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerACLEntryID != nil {
		in, out := &in.LoadBalancerACLEntryID, &out.LoadBalancerACLEntryID
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.RuleAction != nil {
		in, out := &in.RuleAction, &out.RuleAction
		*out = new(string)
		**out = **in
	}
	if in.RuleNumber != nil {
		in, out := &in.RuleNumber, &out.RuleNumber
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerACLEntrySetObservation.
func (in *LoadBalancerACLEntrySetObservation) DeepCopy() *LoadBalancerACLEntrySetObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerACLEntrySetObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerACLEntrySetParameters) DeepCopyInto(out *LoadBalancerACLEntrySetParameters) {
	*out = *in
	if in.CidrBlock != nil {
		in, out := &in.CidrBlock, &out.CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.RuleAction != nil {
		in, out := &in.RuleAction, &out.RuleAction
		*out = new(string)
		**out = **in
	}
	if in.RuleNumber != nil {
		in, out := &in.RuleNumber, &out.RuleNumber
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerACLEntrySetParameters.
func (in *LoadBalancerACLEntrySetParameters) DeepCopy() *LoadBalancerACLEntrySetParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerACLEntrySetParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionObservation) DeepCopyInto(out *SessionObservation) {
	*out = *in
	if in.CookieName != nil {
		in, out := &in.CookieName, &out.CookieName
		*out = new(string)
		**out = **in
	}
	if in.CookieType != nil {
		in, out := &in.CookieType, &out.CookieType
		*out = new(string)
		**out = **in
	}
	if in.SessionPersistencePeriod != nil {
		in, out := &in.SessionPersistencePeriod, &out.SessionPersistencePeriod
		*out = new(float64)
		**out = **in
	}
	if in.SessionState != nil {
		in, out := &in.SessionState, &out.SessionState
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionObservation.
func (in *SessionObservation) DeepCopy() *SessionObservation {
	if in == nil {
		return nil
	}
	out := new(SessionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionParameters) DeepCopyInto(out *SessionParameters) {
	*out = *in
	if in.CookieName != nil {
		in, out := &in.CookieName, &out.CookieName
		*out = new(string)
		**out = **in
	}
	if in.CookieType != nil {
		in, out := &in.CookieType, &out.CookieType
		*out = new(string)
		**out = **in
	}
	if in.SessionPersistencePeriod != nil {
		in, out := &in.SessionPersistencePeriod, &out.SessionPersistencePeriod
		*out = new(float64)
		**out = **in
	}
	if in.SessionState != nil {
		in, out := &in.SessionState, &out.SessionState
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionParameters.
func (in *SessionParameters) DeepCopy() *SessionParameters {
	if in == nil {
		return nil
	}
	out := new(SessionParameters)
	in.DeepCopyInto(out)
	return out
}
