/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EIPObservation struct {

	// the ID of the EIP.
	AllocationID *string `json:"allocationId,omitempty" tf:"allocation_id,omitempty"`

	// The band width of the public address.
	BandWidth *float64 `json:"bandWidth,omitempty" tf:"band_width,omitempty"`

	// the ID of the BWS which the EIP associated.
	BandWidthShareID *string `json:"bandWidthShareId,omitempty" tf:"band_width_share_id,omitempty"`

	// The charge type of the Elastic IP address.Valid Values:'PrePaidByMonth','Monthly','PostPaidByPeak','Peak','PostPaidByDay','Daily','PostPaidByTransfer','TrafficMonthly','DailyPaidByTransfer','HourlySettlement','PostPaidByHour','HourlyInstantSettlement','PostpaidByTime'.
	ChargeType *string `json:"chargeType,omitempty" tf:"charge_type,omitempty"`

	// creation time of the EIP.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// the ID of the EIP.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The instance type to bind with the EIP.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// InternetGateway ID.
	InternetGatewayID *string `json:"internetGatewayId,omitempty" tf:"internet_gateway_id,omitempty"`

	// BWS EIP.
	IsBandWidthShare *string `json:"isBandWidthShare,omitempty" tf:"is_band_width_share,omitempty"`

	// The id of the line.
	LineID *string `json:"lineId,omitempty" tf:"line_id,omitempty"`

	// NetworkInterface ID.
	NetworkInterfaceID *string `json:"networkInterfaceId,omitempty" tf:"network_interface_id,omitempty"`

	// The id of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The Elastic IP address.
	PublicIP *string `json:"publicIp,omitempty" tf:"public_ip,omitempty"`

	// Purchase time. If charge_type is Monthly or PrePaidByMonth, this is Required.
	PurchaseTime *float64 `json:"purchaseTime,omitempty" tf:"purchase_time,omitempty"`

	// state of the EIP.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// the tags of the resource.
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type EIPParameters struct {

	// The band width of the public address.
	// +kubebuilder:validation:Optional
	BandWidth *float64 `json:"bandWidth,omitempty" tf:"band_width,omitempty"`

	// The charge type of the Elastic IP address.Valid Values:'PrePaidByMonth','Monthly','PostPaidByPeak','Peak','PostPaidByDay','Daily','PostPaidByTransfer','TrafficMonthly','DailyPaidByTransfer','HourlySettlement','PostPaidByHour','HourlyInstantSettlement','PostpaidByTime'.
	// +kubebuilder:validation:Optional
	ChargeType *string `json:"chargeType,omitempty" tf:"charge_type,omitempty"`

	// The id of the line.
	// +kubebuilder:validation:Optional
	LineID *string `json:"lineId,omitempty" tf:"line_id,omitempty"`

	// The id of the project.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Purchase time. If charge_type is Monthly or PrePaidByMonth, this is Required.
	// +kubebuilder:validation:Optional
	PurchaseTime *float64 `json:"purchaseTime,omitempty" tf:"purchase_time,omitempty"`

	// the tags of the resource.
	// +kubebuilder:validation:Optional
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// EIPSpec defines the desired state of EIP
type EIPSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EIPParameters `json:"forProvider"`
}

// EIPStatus defines the observed state of EIP.
type EIPStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EIPObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// EIP is the Schema for the EIPs API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,ksyun}
type EIP struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.bandWidth)",message="bandWidth is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.chargeType)",message="chargeType is a required parameter"
	Spec   EIPSpec   `json:"spec"`
	Status EIPStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EIPList contains a list of EIPs
type EIPList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EIP `json:"items"`
}

// Repository type metadata.
var (
	EIP_Kind             = "EIP"
	EIP_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EIP_Kind}.String()
	EIP_KindAPIVersion   = EIP_Kind + "." + CRDGroupVersion.String()
	EIP_GroupVersionKind = CRDGroupVersion.WithKind(EIP_Kind)
)

func init() {
	SchemeBuilder.Register(&EIP{}, &EIPList{})
}
