//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALB) DeepCopyInto(out *ALB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALB.
func (in *ALB) DeepCopy() *ALB {
	if in == nil {
		return nil
	}
	out := new(ALB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ALB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALBList) DeepCopyInto(out *ALBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ALB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALBList.
func (in *ALBList) DeepCopy() *ALBList {
	if in == nil {
		return nil
	}
	out := new(ALBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ALBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALBObservation) DeepCopyInto(out *ALBObservation) {
	*out = *in
	if in.ALBName != nil {
		in, out := &in.ALBName, &out.ALBName
		*out = new(string)
		**out = **in
	}
	if in.ALBType != nil {
		in, out := &in.ALBType, &out.ALBType
		*out = new(string)
		**out = **in
	}
	if in.ALBVersion != nil {
		in, out := &in.ALBVersion, &out.ALBVersion
		*out = new(string)
		**out = **in
	}
	if in.ChargeType != nil {
		in, out := &in.ChargeType, &out.ChargeType
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.EnabledLog != nil {
		in, out := &in.EnabledLog, &out.EnabledLog
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IPVersion != nil {
		in, out := &in.IPVersion, &out.IPVersion
		*out = new(string)
		**out = **in
	}
	if in.KlogInfo != nil {
		in, out := &in.KlogInfo, &out.KlogInfo
		*out = make([]KlogInfoObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.PublicIP != nil {
		in, out := &in.PublicIP, &out.PublicIP
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALBObservation.
func (in *ALBObservation) DeepCopy() *ALBObservation {
	if in == nil {
		return nil
	}
	out := new(ALBObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALBParameters) DeepCopyInto(out *ALBParameters) {
	*out = *in
	if in.ALBName != nil {
		in, out := &in.ALBName, &out.ALBName
		*out = new(string)
		**out = **in
	}
	if in.ALBType != nil {
		in, out := &in.ALBType, &out.ALBType
		*out = new(string)
		**out = **in
	}
	if in.ALBVersion != nil {
		in, out := &in.ALBVersion, &out.ALBVersion
		*out = new(string)
		**out = **in
	}
	if in.ChargeType != nil {
		in, out := &in.ChargeType, &out.ChargeType
		*out = new(string)
		**out = **in
	}
	if in.EnabledLog != nil {
		in, out := &in.EnabledLog, &out.EnabledLog
		*out = new(bool)
		**out = **in
	}
	if in.IPVersion != nil {
		in, out := &in.IPVersion, &out.IPVersion
		*out = new(string)
		**out = **in
	}
	if in.KlogInfo != nil {
		in, out := &in.KlogInfo, &out.KlogInfo
		*out = make([]KlogInfoParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALBParameters.
func (in *ALBParameters) DeepCopy() *ALBParameters {
	if in == nil {
		return nil
	}
	out := new(ALBParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALBSpec) DeepCopyInto(out *ALBSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALBSpec.
func (in *ALBSpec) DeepCopy() *ALBSpec {
	if in == nil {
		return nil
	}
	out := new(ALBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALBStatus) DeepCopyInto(out *ALBStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALBStatus.
func (in *ALBStatus) DeepCopy() *ALBStatus {
	if in == nil {
		return nil
	}
	out := new(ALBStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlogInfoObservation) DeepCopyInto(out *KlogInfoObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.LogPoolName != nil {
		in, out := &in.LogPoolName, &out.LogPoolName
		*out = new(string)
		**out = **in
	}
	if in.ProjectName != nil {
		in, out := &in.ProjectName, &out.ProjectName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlogInfoObservation.
func (in *KlogInfoObservation) DeepCopy() *KlogInfoObservation {
	if in == nil {
		return nil
	}
	out := new(KlogInfoObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlogInfoParameters) DeepCopyInto(out *KlogInfoParameters) {
	*out = *in
	if in.LogPoolName != nil {
		in, out := &in.LogPoolName, &out.LogPoolName
		*out = new(string)
		**out = **in
	}
	if in.ProjectName != nil {
		in, out := &in.ProjectName, &out.ProjectName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlogInfoParameters.
func (in *KlogInfoParameters) DeepCopy() *KlogInfoParameters {
	if in == nil {
		return nil
	}
	out := new(KlogInfoParameters)
	in.DeepCopyInto(out)
	return out
}
