/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CertificateObservation struct {

	// certificate authority.
	CertAuthority *string `json:"certAuthority,omitempty" tf:"cert_authority,omitempty"`

	// The ID of the certificate.
	CertificateID *string `json:"certificateId,omitempty" tf:"certificate_id,omitempty"`

	// The name of the certificate.
	CertificateName *string `json:"certificateName,omitempty" tf:"certificate_name,omitempty"`

	// The common name on the certificate.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// The expire time of the certificate.
	ExpireTime *string `json:"expireTime,omitempty" tf:"expire_time,omitempty"`
}

type CertificateParameters struct {

	// The ID of the certificate.
	// +kubebuilder:validation:Required
	CertificateID *string `json:"certificateId" tf:"certificate_id,omitempty"`
}

type ListenerCertGroupObservation struct {

	// The ID of the ALB Listener Cert Group.
	ALBListenerCertGroupID *string `json:"albListenerCertGroupId,omitempty" tf:"alb_listener_cert_group_id,omitempty"`

	// The ID of the ALB Listener.
	ALBListenerID *string `json:"albListenerId,omitempty" tf:"alb_listener_id,omitempty"`

	Certificate []CertificateObservation `json:"certificate,omitempty" tf:"certificate,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ListenerCertGroupParameters struct {

	// The ID of the ALB Listener.
	// +kubebuilder:validation:Optional
	ALBListenerID *string `json:"albListenerId,omitempty" tf:"alb_listener_id,omitempty"`

	// +kubebuilder:validation:Optional
	Certificate []CertificateParameters `json:"certificate,omitempty" tf:"certificate,omitempty"`
}

// ListenerCertGroupSpec defines the desired state of ListenerCertGroup
type ListenerCertGroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ListenerCertGroupParameters `json:"forProvider"`
}

// ListenerCertGroupStatus defines the observed state of ListenerCertGroup.
type ListenerCertGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ListenerCertGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ListenerCertGroup is the Schema for the ListenerCertGroups API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,ksyun}
type ListenerCertGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.albListenerId)",message="albListenerId is a required parameter"
	Spec   ListenerCertGroupSpec   `json:"spec"`
	Status ListenerCertGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ListenerCertGroupList contains a list of ListenerCertGroups
type ListenerCertGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ListenerCertGroup `json:"items"`
}

// Repository type metadata.
var (
	ListenerCertGroup_Kind             = "ListenerCertGroup"
	ListenerCertGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ListenerCertGroup_Kind}.String()
	ListenerCertGroup_KindAPIVersion   = ListenerCertGroup_Kind + "." + CRDGroupVersion.String()
	ListenerCertGroup_GroupVersionKind = CRDGroupVersion.WithKind(ListenerCertGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&ListenerCertGroup{}, &ListenerCertGroupList{})
}
