/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/kingsoftcloud/provider-ksyun/apis/alb/v1alpha1"
	v1alpha1ebs "github.com/kingsoftcloud/provider-ksyun/apis/ebs/v1alpha1"
	v1alpha1eip "github.com/kingsoftcloud/provider-ksyun/apis/eip/v1alpha1"
	v1alpha1kcm "github.com/kingsoftcloud/provider-ksyun/apis/kcm/v1alpha1"
	v1alpha1kec "github.com/kingsoftcloud/provider-ksyun/apis/kec/v1alpha1"
	v1alpha1slb "github.com/kingsoftcloud/provider-ksyun/apis/slb/v1alpha1"
	v1alpha1apis "github.com/kingsoftcloud/provider-ksyun/apis/v1alpha1"
	v1beta1 "github.com/kingsoftcloud/provider-ksyun/apis/v1beta1"
	v1alpha1vpc "github.com/kingsoftcloud/provider-ksyun/apis/vpc/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1ebs.SchemeBuilder.AddToScheme,
		v1alpha1eip.SchemeBuilder.AddToScheme,
		v1alpha1kcm.SchemeBuilder.AddToScheme,
		v1alpha1kec.SchemeBuilder.AddToScheme,
		v1alpha1slb.SchemeBuilder.AddToScheme,
		v1alpha1apis.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1vpc.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
