apiVersion: vpc.kingsoftcloud.io/v1alpha1
kind: SecurityGroup
metadata:
  name: example-kec-security-group-1
spec:
  forProvider:
    securityGroupName: "test-crossplane-kec-security-group"
    vpcIdRef:
      name: "example-kec-vpc-1"